INSERT INTO QUESTION (ID, TITLE) VALUES (1, 'testQuestion1');
INSERT INTO QUESTION (ID, TITLE) VALUES (2, 'testQuestion2');
INSERT INTO QUESTION_ANSWERS (ID, ANSWER) VALUES (1, '1_answer1');
INSERT INTO QUESTION_ANSWERS (ID, ANSWER) VALUES (1, '1_answer2');
INSERT INTO QUESTION_ANSWERS (ID, ANSWER) VALUES (1, '1_answer3');
INSERT INTO QUESTION_ANSWERS (ID, ANSWER) VALUES (2, '2_answer1');
INSERT INTO QUESTION_ANSWERS (ID, ANSWER) VALUES (2, '2_answer2');